In [ ]:
import numpy as np
import simulator
import estimator

In [57]:
sim = simulator.GNAR_simulator(N=100, T=300, G=3, network_time_varying=True, CV_time_varying=True)
beta = np.array([[0.15,0.2,-0.1],[0.1,0.3,-0.2],[0.15,0.1,0.3]]).T
v = np.array([0.2,0.4,0.6])
#beta, v, gamma, group = sim.generate_para(beta=beta, v=v)
beta, v, gamma, group = sim.generate_para()
Y, CV, network = sim.generate_data()
est = estimator.GNAR_estimator(Y, CV, network,G=3)
group_est_0 = est.k_means_clustering(method='networkeffect',time_varying=True)
group_est, beta_est = est.update_all_para()
print(beta)
print(v)
print(beta_est)

/Users/ardentem/Desktop/GNAR/estimator.py:113: RuntimeWarning: invalid value encountered in divide
  beta_net[:,1+l] = np.mean(beta_, axis=0) / np.sum(c == l, axis=0)
100%|██████████| 100/100 [00:03<00:00, 26.68it/s]

Epoch 0: 0 nodes updated
Convergence reached
[[0.23457801 0.22121888 0.04764032]
 [0.33318105 0.02456799 0.37209593]
 [0.04396837 0.04075084 0.276216  ]]
[0.53957165 0.7045408  0.42471186]
[[ 0.27675469  0.37250482  0.04731419]
 [ 0.04031485  0.02641971  0.22076745]
 [ 0.04350052  0.33138305  0.23508159]
 [ 0.42439437  0.70449122  0.53957243]
 [-0.37458463  0.7889177  -0.28970793]
 [-0.49728413 -0.64000801  0.31258883]
 [ 0.24437562 -0.10160471  0.3148274 ]
 [ 0.02428095 -0.07410229 -0.07048587]]
